jobs/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from jobs import views

urlpatterns = patterns('',
    # job
    url(r'^add$',
        permission_required('jobs.add_job')
        (views.JobCreate.as_view()),
        name = 'add'
    ),

    url(r'^$',
        permission_required('jobs.read_job')
        (views.JobList.as_view()),
        name = 'index'
    ),

    url(r'^(?P<pk>\d+)$',
        permission_required('jobs.read_job')
        (views.JobDetail.as_view()),
        name = 'detail'
    ),

    url(r'^update/(?P<pk>\d+)$',
        permission_required('jobs.change_job')
        (views.JobUpdate.as_view()),
        name = 'update'
    ),

    url(r'^delete/(?P<pk>\d+)$',
        permission_required('jobs.delete_job')
        (views.JobDelete.as_view()),
        name = 'delete'
    ),

    # Job Allocation
    url(r'^allocate/(?P<session_id>\d+)/(?P<job_id>\d+)$',
        permission_required('jobs.add_joballocation')
        (views.allocate_job),
        name = 'allocate'
    ),

    url(r'^delete/allocation/(?P<pk>\d+)$',
        permission_required('jobs.delete_joballocation')
        (views.JobAllocationDelete.as_view()),
        name = 'allocate-delete'
    ),

    # Job Registration
    url(r'^register/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.register),
        name = 'register'
    ),

    url(r'^unregister/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.unregister),
        name = 'unregister'
    ),
)

kanri/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'dashboard.views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ninjas/', include('ninjas.urls', namespace = "ninjas")),
    url(r'^planner/', include('planner.urls', namespace = "planner")),
    url(r'^attendance/', include('attendance.urls', namespace = "attendance")),
    url(r'^accounts/', include('accounts.urls', namespace = "accounts")),
    url(r'^mentors/', include('mentors.urls', namespace = "mentors")),
    url(r'^jobs/', include('jobs.urls', namespace = "jobs")),
)

mentors/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from mentors import views

urlpatterns = patterns('',
   url(r'^add$',
        permission_required('mentors.add_mentor')
        (views.MentorCreate.as_view()),
        name = 'add'
    ),

    url(r'^upload$',
        permission_required('mentors.add_mentor')
        (views.upload),
        name = 'upload'
    ),

    url(r'^$',
        permission_required('mentors.read_mentor')
        (views.MentorList.as_view()),
        name = 'index'
    ),

    url(r'^dashboard$',
        permission_required('mentors.view_mentor_dashboard')
        (views.dashboard),
        name = 'dashboard'
    ),

    url(r'^(?P<pk>\d+)$',
        permission_required('mentors.read_mentor')
        (views.MentorDetail.as_view()),
        name = 'detail'
    ),
    
    url(r'^update/(?P<pk>\d+)$',
        permission_required('mentors.change_mentor')
        (views.MentorUpdate.as_view()),
        name = 'update'
    ),
    
    url(r'^delete/(?P<pk>\d+)$',
        permission_required('mentors.delete_mentor')
        (views.MentorDelete.as_view()),
        name = 'delete'
    ),



    url(r'^role/add$',
        permission_required('mentors.add_role')
        (views.RoleCreate.as_view()),
        name = 'role-add'
    ),

    url(r'^role$',
        permission_required('mentors.read_role')
        (views.RoleList.as_view()),
        name = 'role-index'
    ),
    
    url(r'^role/(?P<pk>\d+)$',
        permission_required('mentors.read_role')
        (views.RoleDetail.as_view()),
        name = 'role-detail'
    ),
    
    url(r'^role/update/(?P<pk>\d+)$',
        permission_required('mentors.change_role')
        (views.RoleUpdate.as_view()),
        name = 'role-update'
    ),

    url(r'^delete/(?P<pk>\d+)$',
        permission_required('mentors.delete_role')
        (views.RoleDelete.as_view()),
        name = 'role-delete'
    ),
)

mentors/models.py
from django.db import models
from planner.models import DojoSession, Shift, DojoTerm
from django.conf import settings
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils import timezone
from jobs.models import Job
import datetime

class Role(models.Model):
    """A role somebody can take in a CoderDojo term."""
    name = models.CharField(max_length = 50, blank = False, help_text = "The name of the role.")
    short_name = models.CharField(max_length = 10, blank = False, help_text = "A short name for this role. Used in spreadsheets.")
    description = models.TextField(max_length = 1024, blank = True, help_text = "The role's long description.")

    def get_absolute_url(self):
        return reverse_lazy('mentors:role-detail', args = [self.id])

    def __unicode__(self):
        return self.name

    class Meta():
        permissions = {
            ('read_role', "Can view a Role entry"),
        }

class Mentor(models.Model):
    MALE_SMALL = "MS"
    MALE_MEDIUM = "MM"
    MALE_LARGE = "ML"
    MALE_EXTRA_LARGE = "MXL"

    FEMALE_EXTRA_SMALL = "FXS"
    FEMALE_SMALL = "FS"
    FEMALE_MEDIUM = "FM"
    FEMALE_LARGE = "FL"
    FEMALE_EXTRA_LARGE = "FXL"

    SHIRT_SIZE_CHOICES = (
        ('Male', (
            (MALE_SMALL, "Male S"),
            (MALE_MEDIUM, "Male M"),
            (MALE_LARGE, "Male L"),
            (MALE_EXTRA_LARGE, "Male XL")
        )),
        ('Female', (
            (FEMALE_EXTRA_SMALL, "Female XS"),
            (FEMALE_SMALL, "Female S"),
            (FEMALE_MEDIUM, "Female M"),
            (FEMALE_LARGE, "Female L"),
            (FEMALE_EXTRA_LARGE, "Female XL")
        ))
    )

    ASSOCIATE = 'A'
    STAFF = 'S'
    NEITHER = 'N'

    CURTIN_STATUS_CHOICES = (
        (ASSOCIATE, 'Associate'),
        (STAFF, 'Staff'),
        (NEITHER, 'Neither/not sure')
    )

    NOTHING = 'NO'
    SOMETHING = 'SO'
    EVERYTHING = 'EV'

    KNOWLEDGE_CHOICES = (
        (NOTHING, 'I know nothing but am keen to learn!'),
        (SOMETHING, 'I know some basics'),
        (EVERYTHING, 'I know a great deal')
    )

    uni = models.CharField(
        max_length = 50,
        null = True,
        blank = True,
        help_text = "University of study"
    )

    uni_study = models.CharField(
        max_length = 256,
        null = True,
        blank = True,
        help_text = "If you're attending university, what are you studying?"
    )
   
    work = models.CharField(
        max_length = 256,
        null = True,
        blank = True,
        help_text = "If you workwhat do you do?"
    )

    shirt_size = models.CharField(
        max_length = 3,
        blank = True,
        choices = SHIRT_SIZE_CHOICES,
        help_text = "T-shirt size (for uniform)"
    )

    needs_shirt = models.BooleanField(
        default = True,
        help_text = "Does the mentor need to have a shirt provisioned for them?"
    )

    wwcc = models.CharField(
        max_length = 10,
        verbose_name = "WWCC card number",
        blank = True,
        null = True,
        help_text = "WWCC card number (if WWCC card holder)"
    )

    wwcc_receipt = models.CharField(
        max_length = 15,
        verbose_name = "WWCC receipt number",
        blank = True,
        null = True,
        help_text = "WWCC receipt number (if WWCC is processing)"
    )

    curtin_status = models.CharField(
        max_length = 1,
        verbose_name = "Current Curtin HR status",
        choices = CURTIN_STATUS_CHOICES,
        default = NEITHER,
        blank = False,
        help_text = "When possible, we recommend that all CoderDojo mentors are either Curtin University Associates or Staff members."
    )

    curtin_id = models.CharField(
        max_length = 10,
        verbose_name = "Curtin Staff/Associate ID",
        blank = True,
        null = True,
        help_text = "Your Curtin Staff/Associate ID (if applicable)"
    )

    coding_experience = models.CharField(
        max_length = 2,
        blank = False,
        default = NOTHING,
        choices = KNOWLEDGE_CHOICES,
        help_text = "How much programming experience do you have?"
    )

    children_experience = models.CharField(
        max_length = 2,
        blank = False,
        default = NOTHING,
        choices = KNOWLEDGE_CHOICES,
        help_text = "How much experience do you have with children?"
    )

    roles_desired = models.ManyToManyField(Role)

    jobs_desired = models.ManyToManyField(Job)

    shift_availabilities = models.ManyToManyField(
        DojoSession,
        help_text = "When are you available?"
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL,
        unique = True
    )

    def name(self):
        return self.user.get_short_name()

    def get_call_url(self):
        return "tel:%s" % self.user.phone_number

    def get_email_url(self):
        return "mailto:%s" % self.user.email

    def get_wwcc_status(self):
        if self.wwcc:
            return "Recorded (%s)" % self.wwcc
        elif self.wwcc_receipt:
            return 'Processing (%s)' % self.wwcc_receipt
        else:
            return 'None'

    def get_curtin_status(self):
        if self.curtin_id and self.curtin_status != self.NEITHER:
            return "%s (%s)" % (self.get_curtin_status_display(), self.curtin_id)
        else:
            return "%s" % self.get_curtin_status_display()
    
    def get_roles_desired(self):
        return ', '.join(self.roles_desired.values_list('name', flat = True))

    def get_future_shifts(self):
        return Shift.objects.filter(mentor = self, session__date__gt = timezone.now())

    def get_future_availabilities(self):
        return self.shift_availabilities.filter(date__gt = timezone.now())

    def get_rostered_hours_per_term(self):
        terms = []
        for term in DojoTerm.objects.all():
            # Build a dict for each term to hold total hours.
            term_info = {
                'term': term,
                'hours': datetime.timedelta()
            }

            # Get all shifts the mentor undertakes in the selected term and
            # total up the starting and ending times for said shifts.
            shifts = Shift.objects.filter(mentor = self, session__term = term)
            for shift in shifts:
                term_info['hours'] += shift.get_duration()

            terms.append(term_info)
        return terms

    def __unicode__(self):
        return self.name()

    def get_absolute_url(self):
        return reverse_lazy('mentors:detail', current_app = 'mentors', args = [self.id])

    @classmethod
    def get_mentor_for_user(cls, user):
        return cls.objects.get(user = user)

    class Meta():
        permissions = {
            ('read_mentor', "Can view a Mentor entry"),
            ('view_mentor_dashboard', 'Can access the Mentor dashboard'),
        }
        ordering = ['user__first_name']

mentors/forms.py
from django import forms
import csv
from csvvalidator import *

class CSVImportForm(forms.Form):
	csv = forms.FileField(required = True, label = "CSV file", help_text = "A valid CSV file from the CoderDojo @ Curtin mentor signup sheet.")

	def is_valid(self):
		csvfile = self.files.get('csv')
		try:
			dialect = csv.Sniffer().sniff(csvfile.read(2048))
		except csv.Error:
			return False
		csvfile.seek(0)
		reader = csv.reader(csvfile, dialect=dialect)		
		fields = (
			"Timestamp",
			"Full name",
			"Email address",
			"Roles",
			"Availability [Saturday 2 August]",
			"Availability [Saturday 9 August]",
			"Availability [Saturday 16 August]",
			"Availability [Saturday 23 August]",
			"Availability [Saturday 30 August]",
			"Availability [Saturday 6 September]",
			"Availability [Saturday 13 September]",
			"Availability [Saturday 20 September]",
			"Mobile number",
			"Gender",
			"T-shirt size",
			"Background",
			"University",
			"Study",
			"Work",
			"WWCC",
			"WWCC Number",
			"Curtin Status",
			"Curtin Associate/Staff ID",
			"Referral",
			"Coding Experience",
			"Child-Related Experience",
			"Coding Knowledge/Interest",
			"Experience with Young People",
			"Aim",
			"Confirmation")

		val = CSVValidator(fields)

		val.add_header_check('EX1', 'bad header')
		val.add_record_length_check('EX2', 'unexpected record length')
		status = val.validate(reader)
		csvfile.seek(0)
		if len(status) is 0:
			return True
		else:
			return False

mentors/templates/mentors/detail.html
{% extends "generic_detail.html" %}
{% load display_pair %}
{% load nicebool %}
{% load bootstrap3 %}

{% block custom_buttons_before %}
	<a href="{{ object.get_call_url }}" class="btn btn-default">
		{% bootstrap_icon 'earphone' %} Call {{ object.user.get_short_name }}
	</a>

	<a href="{{ object.get_email_url }}" class="btn btn-default">
		{% bootstrap_icon 'envelope' %} Email {{ object.user.get_short_name }}
	</a>
{% endblock %}

{% block list_url %}{% url 'mentors:index' %}{% endblock %}
{% block edit_url %}{% url 'mentors:update' object.id %}{% endblock %}
{% block delete_url %}{% url 'mentors:delete' object.id %}{% endblock %}

{% block detail %}
	<h2>Personal Information</h2>
	{{ object.user.first_name|display_pair:'First Name' }}
	{{ object.user.last_name|display_pair:'Last Name' }}
	{{ object.get_shirt_size_display|display_pair:"Shirt Size" }}
	{{ object.needs_shirt|display_pair:"Needs Shirt"}}

	<h2>Contact Information</h2>
	{{ object.user.email|display_pair:'Email' }}
	{{ object.user.phone_number|display_pair:'Phone Number' }}

	<h2>Roles, Availability, and Shifts</h2>
	{{ object.get_roles_desired|display_pair:"Desired Roles" }}

	<div class="form-group">
		<label class="col-sm-2 control-label">Shifts</label>
		<div class="col-sm-10">
			<p class="form-control-static">
				{% for shift in object.get_future_shifts %}
					<a href="{{ shift.get_future_shifts }}">{{ shift }}</a><br />
				{% endfor %}
			</p>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">Future Availabilities</label>
		<div class="col-sm-10">
			<p class="form-control-static">
				{% for session in object.get_future_availabilities %}
					<a href="{{ session.get_absolute_url }}">{{ session }}</a><br />
				{% endfor %}
			</p>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-2 control-label">Hours Volunteered</label>
		<div class="col-sm-10">
			<p class="form-control-static">
				{% for term in object.get_rostered_hours_per_term %}
					<a href="{{ term.get_absolute_url }}">{{ term.term }}</a>: {{ term.hours }}<br />
				{% endfor %}
			</p>
		</div>
	</div>

	<h2>Background</h2>
	{{ object.uni|display_pair:'University' }}
	{{ object.uni_study|display_pair:'Field of Study' }}
	{{ object.work|display_pair:'Occupation' }}
	{{ object.get_coding_experience_display|display_pair:'Coding Experience' }}
	{{ object.get_children_experience_display|display_pair:'Children Experience' }}

	<h2>Legal and HR</h2>
	{{ object.get_wwcc_status|display_pair:'WWCC Status' }}
	{{ object.get_curtin_status|display_pair:'Curtin Status' }}
{% endblock %}

mentors/templates/mentors/index.html
{% extends "generic_list.html" %}

{% load bootstrap3 %}
{% load nicebool %}
{% load staticfiles %}

{% block add_url %}{% url 'mentors:add' %}{% endblock %}
{% block custom_buttons_after %}
	<button class="btn btn-default" onclick="loadFile('#id_csv');">{% bootstrap_icon "cloud-upload" %} Import Spreadsheet</button>
	<a href="{% url 'mentors:role-index' %}" class="btn btn-default">{% bootstrap_icon "tasks" %} Manage Roles</a>

	<div class="hidden">
		<form id="csv-form" action="{% url 'mentors:upload' %}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<input id="id_csv" name="csv" accept="text/csv" onchange="submitFile('#csv-form');" type="file" />
			<input type="submit" class="btn btn-default" />
		</form>
	</div>
{% endblock %}

{% block list %}
<thead>
	<th>Name</th>
	<th>Email</th>
	<th>Number</th>
	<th>Needs Shirt</th>
	<th>Size</th>
	<th>WWCC</th>
	{% for role in roles %}
		<th>{{role.short_name}}</th>
	{% endfor %}
</thead>
<tbody>
	{% for mentor in object_list %}
		<tr>
			<td><a href="{% url 'mentors:detail' mentor.id %}">{{ mentor.name }}</a></td>
			<td><a href="{{ mentor.get_email_url }}">{{ mentor.user.email }}</a></td>
			<td><a href="{{ mentor.get_call_url }}">{{ mentor.user.phone_number }}</td>
			<td class="text-center">{{ mentor.needs_shirt|nicebool }}</td>
			<td>{{ mentor.get_shirt_size_display|default:"—" }}</td>
			<td>{{ mentor.get_wwcc_status }}</td>
			{% for role in roles %}
				<td class="text-center">
					{% if role in mentor.roles_desired.all %}
						{% bootstrap_icon "ok" %}
					{% else %}
						{% bootstrap_icon "remove" %}
					{% endif %}
				</td>
			{% endfor %}
		</tr>
	{% endfor %}
</tbody>
{% endblock %}

{% block custom_js %}
<script src="{% static 'js/Upload.js' %}">

</script>
{% endblock %}

mentors/templates/mentors/role_detail.html
{% extends "generic_detail.html" %}
{% load display_pair %}

{% block list_url %}{% url 'mentors:role-index' %}{% endblock %}
{% block edit_url %}{% url 'mentors:role-update' object.id %}{% endblock %}
{% block delete_url %}{% endblock %}


{% block detail %}
	{{ object.name|display_pair:'Name' }}
	{{ object.short_name|display_pair:'Short Name' }}
	{{ object.description|display_pair:'Description' }}
{% endblock %}

mentors/templates/mentors/role_index.html
{% extends "generic_list.html" %}

{% load bootstrap3 %}

{% block add_url %}{% url 'mentors:role-add' %}{% endblock %}

{% block list %}
	<thead>
		<th class="col-md-2">Name</th>
		<th class="col-md-2">Short Name</th>
		<th class="col-md-7">Description</th>
		<th class="col-md-1"></th>
	</thead>
	<tbody>
		{% for role in object_list %}
			<tr>
				<td>{{ role.name }}</td>
				<td>{{ role.short_name }}</td>
				<td>{{ role.description }}</td>
				<td>
					<a href="{% url 'mentors:role-update' role.id %}">{% bootstrap_icon "pencil" %}</a>
				</td>
			</tr>
		{% endfor %}
	</tbody>
{% endblock %}