accounts/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from accounts import views

urlpatterns = patterns('',
    #url(r'^$', views.index, name = 'index'),
    url(r'^login/?$',
    	views.login,
    	name = 'login'
    ),
    
    url(r'^logout/?$',
    	views.logout,
    	name = 'logout'
    ),
    

    url(r'^admin$',
        permission_required('accounts.see_admin')
    	(views.admin),
    	name = 'admin'
    ),

    url(r'^admin/pass$',
        permission_required('accounts.change_user_password')
        (views.change_password_admin),
        name = 'admin-password'
    ),

    url(r'^admin/resetpass$',
        permission_required('accounts.reset_user_password')
        (views.admin_reset_password),
        name = 'admin-reset-password'
   ),

    url(r'^admin/sync$',
        permission_required('accounts.sync_permissions')
    	(views.sync),
    	name = 'permissions-sync'
    ),

    url(r'^admin/management/add$',
        permission_required('accounts.add_management')
    	(views.management_add),
    	name = 'management-add',
    ),

    url(r'^admin/management/remove$',
        permission_required('accounts.remove_management')
    	(views.management_remove),
    	name = 'management-remove',
    ),
)

jobs/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from jobs import views

urlpatterns = patterns('',
    # job
    url(r'^add$',
        permission_required('jobs.add_job')
        (views.JobCreate.as_view()),
        name = 'add'
    ),

    url(r'^$',
        permission_required('jobs.read_job')
        (views.JobList.as_view()),
        name = 'index'
    ),

    url(r'^(?P<pk>\d+)$',
        permission_required('jobs.read_job')
        (views.JobDetail.as_view()),
        name = 'detail'
    ),

    url(r'^update/(?P<pk>\d+)$',
        permission_required('jobs.change_job')
        (views.JobUpdate.as_view()),
        name = 'update'
    ),

    url(r'^delete/(?P<pk>\d+)$',
        permission_required('jobs.delete_job')
        (views.JobDelete.as_view()),
        name = 'delete'
    ),

    # Job Allocation
    url(r'^allocate/(?P<session_id>\d+)/(?P<job_id>\d+)$',
        permission_required('jobs.add_joballocation')
        (views.allocate_job),
        name = 'allocate'
    ),

    url(r'^delete/allocation/(?P<pk>\d+)$',
        permission_required('jobs.delete_joballocation')
        (views.JobAllocationDelete.as_view()),
        name = 'allocate-delete'
    ),

    # Job Registration
    url(r'^register/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.register),
        name = 'register'
    ),

    url(r'^unregister/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.unregister),
        name = 'unregister'
    ),
)

kanri/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'dashboard.views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ninjas/', include('ninjas.urls', namespace = "ninjas")),
    url(r'^planner/', include('planner.urls', namespace = "planner")),
    url(r'^attendance/', include('attendance.urls', namespace = "attendance")),
    url(r'^accounts/', include('accounts.urls', namespace = "accounts")),
    url(r'^mentors/', include('mentors.urls', namespace = "mentors")),
    url(r'^jobs/', include('jobs.urls', namespace = "jobs")),
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class KanriUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password = None):
        user = self.model(
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name
        )

        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.model(
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            password = password
        )

        user.is_superuser = True
        user.is_staff = True

        user.set_password(password)
        user.save(using = self._db)
        return user


class KanriUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        max_length = 254,
        blank = False,
        unique = True,
    )
    
    first_name = models.CharField(
        max_length = 30,
        blank = False,
    )

    last_name = models.CharField(
        max_length = 30,
        blank = False,
    )

    phone_number = models.CharField(
        max_length = 10,
    )

    is_active = models.BooleanField(
        default = True
    )

    is_staff = models.BooleanField(
        default = False
    )

    objects = KanriUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_full_name(self):
        return "%s %s" % (self.first_name, self.last_name)

    def get_short_name(self):
        return "%s %s" % (self.first_name, self.last_name[0])

    class Meta():
        permissions = {
            ('see_admin', "User can see the admin page"),
            ('change_user_passowrd', "Can change any user's password"),
            ('add_management', "Can add a user to the Management group"),
            ('remove_management', "Can remove a user from the Management group"),
            ('sync_permissions', "Can sync permissions"),
        }

    def __unicode__(self):
        return self.get_full_name()

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.models import Group

class LoginForm(forms.Form):
    error_css_class = ""
    email = forms.EmailField(
        widget = forms.TextInput(attrs = {
            'class': 'form-control input-lg',
            'placeholder': 'Email Address'}),
        max_length = 140,
        required = True
        )

    password = forms.CharField(
        widget = forms.PasswordInput(attrs = {
            'class': 'form-control input-lg',
            'placeholder': 'Password'})
        )
    
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')
        if email and password:
            self.user = authenticate(email=email, password=password)
            if self.user is not None:
                if self.user.is_active:
                    print "active user"
                    return cleaned_data
                else:
                    print "disabled user"
                    raise forms.ValidationError('User has been disabled.', code = 'disabled')
            else:
                print "invalid user"
                raise forms.ValidationError('Invalid email/password combination.', code = 'invalid')

class UserSelectionForm(forms.Form):
    user = forms.ModelChoiceField(
        get_user_model().objects.all(),
        widget = forms.Select(attrs = {
            'class': 'col-md-4'
            })
        )

class ManagementSelectionForm(forms.Form):
    user = forms.ModelChoiceField(
        Group.objects.get_or_create(name = 'Management')[0].user_set.all(),
        widget = forms.Select(attrs = {
            'class': 'col-md-4'
        })
    )

class ChangePasswordForm(forms.Form):
    user = forms.ModelChoiceField(
        get_user_model().objects.all(),
        widget = forms.Select(attrs = {
            'class': 'col-md-4'
        })
    )
    password = forms.CharField(
        widget = forms.PasswordInput(attrs = {
            'class': 'col-md-4'
        })
    )

accounts/views.py
from django.shortcuts import render, redirect
from forms import *
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, Permission
from django.core.mail import send_mail
from textwrap import dedent


def login(request):
    # check if user has logged in
    if request.user.is_authenticated():
        return redirect('home')

    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            auth_login(request, form.user)
            return redirect("home")
    else:
        form = LoginForm()
    return render(request, 'accounts/login.html', {
        'form': form
        })

@login_required
def logout(request):
    if request.method == "POST":
        auth_logout(request)
        return redirect('home')
    return render(request, 'accounts/logout.html')

def admin(request):
    add_management_form = UserSelectionForm()
    remove_management_form = ManagementSelectionForm()
    change_password_form = ChangePasswordForm()
    reset_password_form = UserSelectionForm()
    return render(request, 'accounts/admin.html', {
        'add_management_form': add_management_form,
        'remove_management_form': remove_management_form,
        'password_form': change_password_form,
        'reset_password_form': reset_password_form,
        })

def sync(request):
    sync = [
        {
            'group': 'Management',
            'permissions': [
                'add_attendance',
                'read_attendance',
                'change_attendance',
                'delete_attendance',
        
                'add_mentor',
                'read_mentor',
                'change_mentor',
                'delete_mentor',
        
                'add_role',
                'read_role',
                'change_role',
                'delete_role',
        
                'add_ninja',
                'read_ninja',
                'change_ninja',
                'delete_ninja',
        
                'add_dojoterm',
                'read_dojoterm',
                'change_dojoterm',
                'delete_dojoterm',
        
                'add_dojosession',
                'read_dojosession',
                'change_dojosession',
                'delete_dojosession',
        
                'add_shift',
                'read_shift',
                'change_shift',
                'delete_shift',
        
                'add_room',
                'read_room',
                'change_room',
                'delete_room',

                'see_admin',
                'change_user_passowrd',
                'add_management',
                'remove_management',
                'sync_permissions'
            ]
        },
        {
            'group': 'Mentors',
            'permissions': [
                'add_attendance',
                'read_attendance',
                'change_attendance',
                'delete_attendance',
        
                'read_shift',

                'read_dojoterm',
                'read_dojosession',

                'read_room',

                'read_job',
                'register_for_job',

                'view_mentor_dashboard',
            ]
        }
    ]
    

    for s in sync:
        group = Group.objects.get_or_create(name = s['group'])[0]
        group.permissions.clear()
        for permission in s['permissions']:
            perm = Permission.objects.get(codename = permission)
            group.permissions.add(perm)
            print "Added %s to %s" % (perm, group)
        group.save()

    return redirect('accounts:admin')
    
def management_add(request):
    if request.method == 'POST':
        form = UserSelectionForm(request.POST)
        if form.is_valid():
            group = Group.objects.get_or_create(name = 'Management')[0]
            form.cleaned_data['user'].groups.add(group)
            return redirect('accounts:admin')
    else:
        return redirect('accounts:admin')

def management_remove(request):
    if request.method == 'POST':
        form = ManagementSelectionForm(request.POST)
        if form.is_valid():
            group = Group.objects.get_or_create(name = 'Management')[0]
            group.user_set.remove(form.cleaned_data['user'])
            return redirect('accounts:admin')
    else:
        return redirect('accounts:admin')

def change_password_admin(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            u = form.cleaned_data['user']
            u.set_password(form.cleaned_data['password'])
            u.save()
            return redirect('accounts:admin')
    else:
        return redirect('accounts:admin')

def admin_reset_password(request):
    if request.method == 'POST':
        form = UserSelectionForm(request.POST)
        if form.is_valid():
            u = form.cleaned_data['user']
            pw = get_user_model().objects.make_random_password()
            u.set_password(pw)
            u.save()

            message = """Dear %s,

                      Your Kanri password has been reset by %s.

                      Your password has been set to: '%s'.

                      --
                      Kanri
                      https://kanriapp.com
                      """ % (u.first_name, request.user.first_name, pw)

            send_mail(
                subject = 'Kanri Password Reset',
                message = dedent(message),
                from_email = 'kye@kanriapp.com',
                recipient_list = (u.email,),
            )

            return redirect('accounts:admin')
    else:
        return redirect('accounts:admin')

accounts/templates/accounts/admin.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block site_title %}Administration Portal{% endblock %}
{% block body_title %}Administration Portal{% endblock %}

{% block content %}
<h2>Reset Password</h2>
<p>Reset a user's password and email it to them.</p>
<form action="{% url 'accounts:admin-reset-password' %}" method="post" class="form-inline">
	{% csrf_token %}
	{% bootstrap_form reset_password_form layout='inline' %}
	{% buttons %}
		{% bootstrap_button 'Reset Password' button_type='submit' %}
	{% endbuttons %}
</form>

<h2>Change Password</h2>
<p>You can change any user's password using this form.</p>

<form action="{% url 'accounts:admin-password' %}" method="post" class="form-inline">
	{% csrf_token %}
	{% bootstrap_form password_form layout='inline' %}
	{% buttons %}
		{% bootstrap_button 'Change Password' button_type='submit' %}
	{% endbuttons %}
</form>

<h2>Add User to Management</h2>
<p>A management account is required when a user wishes to access mangement functions. For example, Champions or Outreach staff.</p>

<form action="{% url 'accounts:management-add' %}" method="post" class="form-inline">
	{% csrf_token %}
	{% bootstrap_form add_management_form layout='inline' %}
	{% buttons %}
		{% bootstrap_button 'Add to Management' button_type='submit' %}
	{% endbuttons %}
</form>

<h2>Remove User from Management</h2>
<p>Use this form to remove a user from management. They will no longer be able to access managemtn
functionality.</p>
<p><b>Warning:</b> if the user is a Champion, they will still be able to access resources which are
granted to Champions.</p>

<form action="{% url 'accounts:management-remove' %}" method="post" class="form-inline">
	{% csrf_token %}
	{% bootstrap_form remove_management_form layout='inline' %}
	{% buttons %}
		{% bootstrap_button 'Remove from Management' button_type='submit' %}
	{% endbuttons %}
</form>

<h2>Sync Permissions</h2>
<p>Syncing permissions to harcoded policies. This should only be required when you first install Kanri. This will ensure that only the right people can access certain restricted resources.</p>

<a href="{% url 'accounts:permissions-sync' %}" class="btn btn-primary">Sync Permissions</a>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block site_title %} Log In {% endblock %}
{% block body_title %} Log in <b>to your Kanri account</b> {% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-6 col-md-offset-3 well">
			<h1 class="text-center">Enter your details</h1>
			{% if form.errors %}
				<div class="alert alert-danger">
					{{ form.errors }}
				</div>
			{% endif %}
			{% if form.field_errors %}
				<div class="alert alert-danger">
					{{ form.field_errors }}
				</div>
			{% endif %}
			<form method="post">
				{% csrf_token %}
				{% for field in form %}
					<div class="form-group {{ field.errors|yesno:'has-error,'}}">
						{{ field }} <br />
					</div>
				{% endfor %}
				<div class="text-center">
					<input type="submit" class="btn btn-lg btn-primary" value="Log in" />
					<input type="submit" class="btn btn-lg btn-default" value="Forgot Password" />
				</div>
			</form>
		</div>
	</div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "base.html" %}

{% block site_title %} Log Out {% endblock %}
{% block body_title %} Log out <b>of your Kanri account</b> {% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-6 col-md-offset-3 well">
			<h1 class="text-center">Are you sure you want to log out?</h1>
			<form method="post">
				{% csrf_token %}
				<div class="text-center">
					<input type="submit" class="btn btn-lg btn-danger" value="Yep!" />
				</div>
			</form>
		</div>
	</div>
{% endblock %}