jobs/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from jobs import views

urlpatterns = patterns('',
    # job
    url(r'^add$',
        permission_required('jobs.add_job')
        (views.JobCreate.as_view()),
        name = 'add'
    ),

    url(r'^$',
        permission_required('jobs.read_job')
        (views.JobList.as_view()),
        name = 'index'
    ),

    url(r'^(?P<pk>\d+)$',
        permission_required('jobs.read_job')
        (views.JobDetail.as_view()),
        name = 'detail'
    ),

    url(r'^update/(?P<pk>\d+)$',
        permission_required('jobs.change_job')
        (views.JobUpdate.as_view()),
        name = 'update'
    ),

    url(r'^delete/(?P<pk>\d+)$',
        permission_required('jobs.delete_job')
        (views.JobDelete.as_view()),
        name = 'delete'
    ),

    # Job Allocation
    url(r'^allocate/(?P<session_id>\d+)/(?P<job_id>\d+)$',
        permission_required('jobs.add_joballocation')
        (views.allocate_job),
        name = 'allocate'
    ),

    url(r'^delete/allocation/(?P<pk>\d+)$',
        permission_required('jobs.delete_joballocation')
        (views.JobAllocationDelete.as_view()),
        name = 'allocate-delete'
    ),

    # Job Registration
    url(r'^register/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.register),
        name = 'register'
    ),

    url(r'^unregister/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.unregister),
        name = 'unregister'
    ),
)

kanri/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'dashboard.views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ninjas/', include('ninjas.urls', namespace = "ninjas")),
    url(r'^planner/', include('planner.urls', namespace = "planner")),
    url(r'^attendance/', include('attendance.urls', namespace = "attendance")),
    url(r'^accounts/', include('accounts.urls', namespace = "accounts")),
    url(r'^mentors/', include('mentors.urls', namespace = "mentors")),
    url(r'^jobs/', include('jobs.urls', namespace = "jobs")),
)

planner/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from planner import views

urlpatterns = patterns('',
    url(r'^$',
        views.index,
        name = 'index'
    ),

    url(r'^terms/add$',
        permission_required('planner.add_dojoterm')
        (views.add_term),
        name = 'terms-add'
    ),

    url(r'^terms$',
        permission_required('planner.read_dojoterm')
        (views.DojoTermList.as_view()),
        name = 'terms'
    ),

    url(r'^terms/(?P<pk>\d+)$',
        permission_required('planner.read_dojoterm')
        (views.DojoTermDetail.as_view()),
        name = 'terms-detail'
    ),

    url(r'^sessions/(?P<pk>\d+)$',
        permission_required('planner.read_dojosession')
        (views.DojoSessionDetail.as_view()),
        name = 'sessions-detail'
    ),

    url(r'^sessions/delete/(?P<pk>\d+)$',
        permission_required('planner.delete_dojosession')
        (views.DojoSessionDelete.as_view()),
        name = 'sessions-delete'
    ),

    url(r'^terms/delete/(?P<pk>\d+)$',
        permission_required('planner.delete_dojoterm')
        (views.DojoTermDelete.as_view()),
        name = 'terms-delete'
    ),



    url(r'^roster/allocate/(?P<session_id>\d+)/(?P<role_id>\d+)$',
        permission_required('planner.add_shift')
        (views.allocate),
        name = 'allocate'
    ),

    url(r'^roster/(?P<term_id>\d+)$',
        permission_required('planner.read_shift')
        (views.roster),
        name = 'roster'
    ),



    url(r'^shifts/(?P<pk>\d+)$',
        permission_required('planner.read_shift')
        (views.ShiftDetail.as_view()),
        name = 'shifts-detail'
    ),

    url(r'^shifts/delete/(?P<pk>\d+)$',
        permission_required('planner.delete_shift')
        (views.ShiftDelete.as_view()),
        name = 'shifts-delete'
    ),



    url(r'^rooms/add$',
        permission_required('planner.add_room')
        (views.RoomCreate.as_view()),
        name = 'rooms-add',
    ),

    url(r'^rooms$',
        permission_required('planner.read_room')
        (views.RoomList.as_view()),
        name = 'rooms-list',
    ),

    url(r'^rooms/(?P<pk>\d+)$',
        permission_required('planner.read_room')
        (views.RoomDetail.as_view()),
        name = 'rooms-detail'
    ),

    url(r'^rooms/update/(?P<pk>\d+)$',
        permission_required('planner.update_room')
        (views.RoomUpdate.as_view()),
        name = 'rooms-update'
    ),

    url(r'^rooms/delete/(?P<pk>\d+)$',
        permission_required('planner.delete_room')
        (views.RoomDelete.as_view()),
        name = 'rooms-delete'
    ),
)

planner/models.py
from __future__ import division
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse, reverse_lazy
from ninjas.models import Ninja
from attendance.models import Attendance
from jobs.models import *
import datetime

class DojoTerm(models.Model):
    name = models.CharField(max_length = 50, blank = False)

    def get_session_count(self):
        return DojoSession.objects.filter(term = self).count()

    def get_sessions(self):
        return DojoSession.objects.filter(term = self)

    def get_first_session(self):
        sessions = DojoSession.objects.filter(term = self).order_by('date')
        if sessions:
            return sessions[0]

    def get_last_session(self):
        sessions = DojoSession.objects.filter(term = self).order_by('-date')
        if sessions:
            return sessions[0]

    def get_ninjas(self):
        return Ninja.objects.filter(availabilities__term = self).distinct().count()
    
    def get_ratio(self):
        sessions = self.get_sessions()
        total = 0
        for session in sessions:
            total = total + session.get_ratio()
        total /= len(sessions)
        return round(total, 2)

    def get_absolute_url(self):
        return reverse_lazy('planner:terms-detail', current_app = 'planner', args = [self.id])

    def __unicode__(self):
        return self.name

    class Meta():
        permissions = {
            ('read_dojoterm', "Can view a DojoTerm entry"),
        }

class Room(models.Model):
    name = models.CharField(
        blank = False,
        unique = True,
        max_length = 50,
        help_text = 'The name of the room.'
    )

    capacity = models.PositiveIntegerField(
        blank = False,
        help_text = 'The number of ninjas that can fit into the room.'
    )

    def get_sessions(self):
        return DojoSession.objects.filter(rooms = self)

    def get_absolute_url(self):
        return reverse_lazy('planner:rooms-detail', args = [self.id], current_app = 'planner')

    def __unicode__(self):
        return self.name

    class Meta():
        permissions = {
            ('read_room', "Can view a Room entry"),
        }



class DojoSession(models.Model):
    term = models.ForeignKey(DojoTerm, help_text = "Dojo Term")
    date = models.DateField(
        blank = False,
        help_text = "Date during which the session will take place."
    )

    start = models.TimeField(
        blank = False,
        help_text = "Start Time"
    )

    end = models.TimeField(
        blank = False,
        help_text = "End Time"
    )

    rooms = models.ManyToManyField(
        Room,
        blank = True,
        help_text = "The rooms in which this session will be running."
    )

    def coming_up(self):
        return abs((self.date_time_start - timezone.now).total_seconds()) < (2 * 60 * 60) # 2 hours
    
    def get_ratio(self):
        mentoring = self.get_shifts().exclude(room = None)
        if mentoring.count() == 0:
            return None
        else:
            return round(self.ninja_set.count() / mentoring.count(), 2)

    def get_capacity(self):
        capacity = 0
        for room in self.rooms.all():
            capacity += room.capacity
        return capacity

    def get_expected_attendance(self):
        return Ninja.objects.filter(availabilities = self).count()

    def get_expected_attendance_percentage(self):
        ninja_count = Ninja.objects.count()
        if ninja_count != 0:
            return (int)((self.get_expected_attendance() / ninja_count) * 100)
        else:
            return 0

    def get_attendance(self):
        return Attendance.objects.filter(session = self).count()

    def get_attendance_percentage(self):
        ninja_count = Ninja.objects.count()
        if ninja_count != 0:
            return (int)((self.get_attendance() / ninja_count) * 100)
        else:
            return 0

    def get_shifts(self):
        s = Shift.objects.filter(session = self)
        return s

    def get_shifts_for_room(self, room):
        s = Shift.objects.filter(session = self, room = room)
        return s

    def get_shifts_per_room(self):
        l = []

        # Get global shifts.
        l.append({
            'room': None,
            'shifts': self.get_shifts_for_room(None)
        })

        # Get roomed shifts
        rooms = Room.objects.all()
        for room in rooms:
            room_details = {
                'room': room,
                'shifts': self.get_shifts_for_room(room)
            }
            l.append(room_details)
        return l
    
    def get_duration(self):
        return datetime.datetime.combine(datetime.datetime.now(), self.end) - datetime.datetime.combine(datetime.datetime.now(), self.start)

    def get_jobs_by_time(self):
        t = []
        for time in Job.TIME_CHOICES:
            jobs = JobAllocation.objects.filter(
                session = self,
                job__time = time[0]
            )

            t.append({
                'time': time[1],
                'job_allocations': jobs
            })

        return t

    def get_jobs_without_allocations(self):
        return Job.objects.exclude(joballocation__session = self)

    def get_absolute_url(self):
        return reverse_lazy('planner:sessions-detail', current_app = 'planner', args = [self.id])

    def get_short_name(self):
        return self.date.strftime("%d/%m")

    def __unicode__(self):
        return "%s (%s)" % (self.get_short_name(), self.term)

    class Meta():
        permissions = {
            ('read_dojosession', "Can view a DojoSession entry"),
        }

class Shift(models.Model):
    mentor = models.ForeignKey(
        'mentors.Mentor',
        blank = False,
        help_text = 'The mentor unergoing this shift.'
    )

    session = models.ForeignKey(
        DojoSession,
        blank = False,
        help_text = 'The session during which this shift takes place.',
    )

    role = models.ForeignKey(
        'mentors.Role',
        blank = False,
        help_text = "The role that the mentor will be undertaking during this shift.",
    )

    room = models.ForeignKey(
        Room,
        blank = True,
        null = True,
        help_text = "The room, if any, that the mentor will be undertaking the shift in."
    )

    start = models.TimeField(
        blank = False,
        help_text = "Start Time"
    )

    end = models.TimeField(
        blank = False,
        help_text = "End Time"
    )

    def get_duration(self):
        return datetime.datetime.combine(datetime.datetime.now(), self.end) - datetime.datetime.combine(datetime.datetime.now(), self.start)

    def get_absolute_url(self):
        return reverse_lazy('planner:shifts-detail', current_app = 'planner', args = [self.id])

    def roster_name(self):
        return "%s (%s)" % (self.mentor, self.role.short_name)

    def __unicode__(self):
        return "%s (%s) for %s" % (self.mentor, self.role, self.session)

    class Meta():
        permissions = {
            ('read_shift', "Can view a Shift entry"),
        }

planner/forms.py
from django import forms
from planner.models import DojoTerm, Room
from mentors.models import Mentor

class DojoTermForm(forms.Form):
	name = forms.CharField(
		max_length = 50,
		help_text = "A human-readable name for the term.",
	)

	first_session_date = forms.DateField(
		help_text = "The starting date and time of the first session.",
	)
 
	first_session_start = forms.TimeField(
		help_text = "The start time of the first session.",
		input_formats = ['%I:%M %p']
	)

	first_session_end = forms.TimeField(
		help_text = "The end time of the first session.",
		input_formats = ['%I:%M %p']
	)

	rooms = forms.ModelMultipleChoiceField(
		queryset = Room.objects.all(),
		help_text = 'What rooms are available for use during this term?'
	)

	weeks = forms.IntegerField(
		min_value = 1,
		help_text = "The number of weeks the term will run.",
	)

class ShiftAllocationForm(forms.Form):	
	def __init__(self, *args, **kwargs):
		# Grab the custom kwargs out before we call super init.
		# I'm gross, but it stops the strict super.__init__ from crying.
		session = kwargs.pop('session', None)
		role = kwargs.pop('role', None)
		super(ShiftAllocationForm, self).__init__(*args, **kwargs)
		
		self.fields['mentor'] = forms.ModelChoiceField(
			queryset = Mentor.objects.filter(
				shift_availabilities = session,
				roles_desired = role
			)
		)

		self.fields['room'] = forms.ModelChoiceField(
			queryset = session.rooms.all(),
			required = False
		)

		self.fields['start'] = forms.TimeField(
			input_formats = ['%I:%M %p'],
			initial = session.start,
			widget = forms.TimeInput(
				format = '%I:%M %p'
			)
		)

		self.fields['end'] = forms.TimeField(
			input_formats = ['%I:%M %p'],
			initial = session.end,
			widget = forms.TimeInput(
				format = '%I:%M %p'
			)
		)

planner/views.py
from django.shortcuts import render, get_object_or_404
from planner.models import *
from planner.forms import *
from mentors.models import Role
from jobs.models import Job
from kanri.views import *
from django.utils import timezone
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.forms.formsets import formset_factory
import datetime
import time

def index(request):
	return render(request, 'planner/index.html')

## Term ##
def add_term(request):
	if request.method == "POST":
		form = DojoTermForm(request.POST)
		if form.is_valid():
			# Create Term
			t = DojoTerm(name = form.cleaned_data['name'])
			t.save()

			# Create sessions for term.
			first_date = form.cleaned_data['first_session_date']
			start = form.cleaned_data['first_session_start']
			end = form.cleaned_data['first_session_end']
			rooms = form.cleaned_data['rooms']

			curr_date = first_date
			week_td = datetime.timedelta(days = 7)

			for week in range(form.cleaned_data['weeks']):
				s = DojoSession(
					term = t,
					date = curr_date,
					start = start,
					end = end,
				)

				s.save()

				for room in rooms:
					s.rooms.add(room)

				s.save()

				curr_date += week_td

			# We're done here.
			return redirect(t)

	else:
		form = DojoTermForm()

	return render(request, 'planner/term/add.html', {
		'form': form,
	})

class DojoTermList(KanriListView):
	model = DojoTerm
	template_name = 'planner/term/list.html'

class DojoTermDetail(KanriDetailView):
	model = DojoTerm
	template_name = 'planner/term/detail.html'

class DojoTermDelete(KanriDeleteView):
	model = DojoTerm
	success_url = reverse_lazy('planner:terms', current_app = 'planner')

## Shifts ##
def allocate(request, session_id, role_id):
	session = get_object_or_404(DojoSession, pk = session_id)
	role = get_object_or_404(Role, pk = role_id)

	if request.method == 'POST':
		form = ShiftAllocationForm(request.POST, session = session, role = role)

		if form.is_valid():
			s = Shift(
				mentor = form.cleaned_data['mentor'],
				session = session,
				role = role,
				room = form.cleaned_data['room'],
				start = form.cleaned_data['start'],
				end = form.cleaned_data['end']
			)
			
			s.save()
			return redirect('planner:roster', session.term.id)
	else:
		form = ShiftAllocationForm(session = session, role = role)

	return render(request, 'planner/allocate.html', {
		'session': session,
		'role': role,
		'form': form,
	})


def roster(request, term_id):
	term = DojoTerm.objects.get(pk = term_id)
	sessions = DojoSession.objects.filter(term = term)
	roles = Role.objects.all()
	jobs = Job.objects.all

	return render(request, 'planner/roster.html', {
		'term': term,
		'sessions': sessions,
		'roles': roles,
		'jobs': jobs,
	})

class ShiftDetail(KanriDetailView):
	model = Shift
	template_name = 'planner/shift/detail.html'

class ShiftDelete(KanriDeleteView):
	model = Shift
	success_url = reverse_lazy('planner:terms')



## Dojo Sessions ##
class DojoSessionDetail(KanriDetailView):
	model = DojoSession
	template_name = 'planner/session/detail.html'

	def get_context_data(self, **kwargs):
		context = super(DojoSessionDetail, self).get_context_data(**kwargs)
		context['roles'] = Role.objects.order_by('name')
		return context

class DojoSessionDelete(KanriDeleteView):
	model = DojoSession
	success_url = reverse_lazy('planner:terms')

## Room ##
class RoomCreate(KanriCreateView):
	model = Room

class RoomDetail(KanriDetailView):
	model = Room
	template_name = 'planner/room/detail.html'

class RoomList(KanriListView):
	model = Room
	template_name = 'planner/room/list.html'

class RoomUpdate(KanriUpdateView):
	model = Room

class RoomDelete(KanriDeleteView):
	model = Room
	success_url = reverse_lazy('planner:rooms-list')

planner/templates/planner/allocate.html
{% extends 'base.html' %}

{% load bootstrap3 %}
{% load staticfiles %}

{% block site_title %} Add {{ role }} to {{ session }} {% endblock %}
{% block body_title %} Add <b>{{ role }}</b> to <b>{{ session }}</b>{% endblock %}

{% block content %}
	<form action="" method="post" class="form form-horizontal">
		{% csrf_token %}

		{% if form.errors %}
			<div class="alert alert-danger">
				{{ form.errors }}
			</div>
		{% endif %}
		
		{% bootstrap_form form layout='horizontal' %}

		{% buttons %}
			{% bootstrap_button 'Add Shift' button_type='submit' %}
		{% endbuttons %}
	</form>
{% endblock %}

{% block custom_js %}
		<script type="text/javascript" src="{% static 'js/moment.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
        <script type="text/javascript">
            $(function () {
                $('#id_start').datetimepicker({
                	pickDate: false
                });

                $('#id_end').datetimepicker({
                	pickDate: false
                });
            });

        </script>
{% endblock %}

planner/templates/planner/index.html
{% extends 'base.html' %}

{% block site_title %}Planner{% endblock %}
{% block body_title %}Planner{% endblock %}

{% block content %}
<div class="well text-center">
	<a href="{% url 'planner:terms' %}" class="btn btn-primary btn-lg">Terms</a>
	<a href="{% url 'planner:rooms-list' %}" class="btn btn-primary btn-lg">Rooms</a>
</div>
{% endblock %}

planner/templates/planner/roster.html
{% extends 'base.html' %}

{% block site_title %}Roster for {{ term }}{% endblock %}
{% block body_title %}Roster for <b>{{ term }}</b>{% endblock %}

{% block content %}
	<ul class="nav nav-tabs" role="tablist">
		{% for session in sessions %}
		<li><a href="#session_{{ session.id }}" role="tab" data-toggle="tab">{{ session.get_short_name }}</a></li>
		{% endfor %}
	</ul>

	<div class="tab-content">
		{% for session in sessions %}
			<div class="tab-pane" id="session_{{ session.id }}">
				<h2>
					<div class="dropdown">
						{{ session }}
						{% if perms.planner.add_shift or perms.jobs.add_joballocation %}
							<a data-toggle="dropdown" href="#">+</a>
							<ul class="dropdown-menu" role="menu">
								{% if perms.planner.add_shift %}
							 		<li role="presentation" class="dropdown-header">Add Shift Allocation</li>
									{% for role in roles %}
    									<li role="presentation"><a role="menuitem" href="{% url 'planner:allocate' session.id role.id %}">{{ role }}</a></li>
									{% endfor %}
								{% endif %}

								{% if perms.jobs.add_joballocation %}
							 		<li role="presentation" class="dropdown-header">Add Job Allocation</li>
									{% for job in jobs %}
    									<li role="presentation"><a role="menuitem" href="{% url 'jobs:allocate' session.id job.id %}">{{ job }}</a></li>
									{% endfor %}
								{% endif %}
							</ul>
						{% endif %}
					</div>
				</h2>
				<h3>Jobs</h3>
					{% if perms.jobs.add_joballocation and session.get_jobs_without_allocations %}
						<div class="alert alert-danger">
							<h4>Allocation Error</h4>
							<p>You have not allocated mentors to the following jobs:</p>
							<ul>
								{% for job in session.get_jobs_without_allocations %}
									<li>{{ job }}</li>
								{% endfor %}
							</ul>
						</div>
					{% endif %}
				{% if session.get_jobs_by_time %}
					<ul>
						{% for time in session.get_jobs_by_time %}
							<h4>{{ time.time }}</h4>
							{% for allocation in time.job_allocations %}
								<li>
									{{ allocation }}
									<a href="{% url 'jobs:allocate-delete' allocation.id %}">x</a>
								</li>
							{% endfor %}
						{% endfor %}
					</ul>
				{% endif %}

				<h3>Shifts</h3>
				{% for room in session.get_shifts_per_room %}
					<h4>
						{% if room.room %}
							{{ room.room }}
						{% else %}
							Global
						{% endif %}
					</h4>
					{% if room.shifts %}
						<ul>
							{% for shift in room.shifts %}
								<li>
									<a href="{{ shift.get_absolute_url }}">{{ shift.roster_name }}</a>
									{% if shift.mentor.user == user %}
										<span style="color: #f00">*</span>
									{% endif %}
								</li>
							{% endfor %}
						</ul>
					{% else %}
						<p>No shifts in this room.</p>
					{% endif %}
				{% endfor %}
			</div>
		{% endfor %}
	</div>
{% endblock %}