jobs/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from jobs import views

urlpatterns = patterns('',
    # job
    url(r'^add$',
        permission_required('jobs.add_job')
        (views.JobCreate.as_view()),
        name = 'add'
    ),

    url(r'^$',
        permission_required('jobs.read_job')
        (views.JobList.as_view()),
        name = 'index'
    ),

    url(r'^(?P<pk>\d+)$',
        permission_required('jobs.read_job')
        (views.JobDetail.as_view()),
        name = 'detail'
    ),

    url(r'^update/(?P<pk>\d+)$',
        permission_required('jobs.change_job')
        (views.JobUpdate.as_view()),
        name = 'update'
    ),

    url(r'^delete/(?P<pk>\d+)$',
        permission_required('jobs.delete_job')
        (views.JobDelete.as_view()),
        name = 'delete'
    ),

    # Job Allocation
    url(r'^allocate/(?P<session_id>\d+)/(?P<job_id>\d+)$',
        permission_required('jobs.add_joballocation')
        (views.allocate_job),
        name = 'allocate'
    ),

    url(r'^delete/allocation/(?P<pk>\d+)$',
        permission_required('jobs.delete_joballocation')
        (views.JobAllocationDelete.as_view()),
        name = 'allocate-delete'
    ),

    # Job Registration
    url(r'^register/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.register),
        name = 'register'
    ),

    url(r'^unregister/(?P<pk>\d+)$',
        permission_required('jobs.register_for_job')
        (views.unregister),
        name = 'unregister'
    ),
)

kanri/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'dashboard.views.index', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ninjas/', include('ninjas.urls', namespace = "ninjas")),
    url(r'^planner/', include('planner.urls', namespace = "planner")),
    url(r'^attendance/', include('attendance.urls', namespace = "attendance")),
    url(r'^accounts/', include('accounts.urls', namespace = "accounts")),
    url(r'^mentors/', include('mentors.urls', namespace = "mentors")),
    url(r'^jobs/', include('jobs.urls', namespace = "jobs")),
)

jobs/models.py
from django.db import models
from django.core.urlresolvers import reverse_lazy

class Job(models.Model):
    BEFORE = 'B'
    DURING = 'D'
    AFTER = 'A'

    TIME_CHOICES = (
        (BEFORE, 'Before session'),
        (DURING, 'During session'),
        (AFTER, 'After session'),
    )

    name = models.CharField(
        max_length = 50,
        help_text = "The job's name."
    )

    description = models.TextField(
        max_length = 1024,
        help_text = "A description of the job."
    )
    
    location = models.CharField(
        max_length = 50,
        help_text = "The job's location."
    )

    time = models.CharField(
        max_length = 1,
        choices = TIME_CHOICES,
        help_text = "The time during a session at which this job can be carried out."
    )

    def get_absolute_url(self):
    	return reverse_lazy('jobs:detail', args = [self.id])

    def __unicode__(self):
        return self.name

    class Meta():
        permissions = {
            ('read_job', "Can view a Job entry"),
            ('register_for_job', 'Can register themselves a job'),
        }

class JobAllocation(models.Model):
    job = models.ForeignKey(Job,
        help_text = "The job the mentor will be performing."
    )

    mentor = models.ForeignKey('mentors.Mentor',
        help_text = "The mentor that'll be undertaking the job."
    )

    session = models.ForeignKey('planner.DojoSession',
        help_text = "The session during which this job allocation will take place."
    )

    class Meta():
        permissions = {
            ('read_joballocation', "Can view a JobAllocation entry"),
        }

    def __unicode__(self):
        return "%s on %s" % (self.mentor, self.job)

jobs/forms.py
from django import forms
from mentors.models import Mentor

class JobAllocationForm(forms.Form):
	def __init__(self, *args, **kwargs):
		# Grab the custom kwargs out before we call super init.
		# I'm gross, but it stops the strict super.__init__ from crying.
		session = kwargs.pop('session', None)
		job = kwargs.pop('job', None)

		super(JobAllocationForm, self).__init__(*args, **kwargs)
	
		self.fields['mentors'] = forms.ModelMultipleChoiceField(
			queryset = Mentor.objects.filter(
				shift__session = session,
				jobs_desired = job
			).exclude(
				joballocation__session = session,
				joballocation__job__time = job.time,
			)
		)

jobs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from jobs.models import *
from jobs.forms import *
from mentors.models import *
from planner.models import DojoSession
from django.core.urlresolvers import reverse_lazy
from kanri.views import *
from django.http import Http404


# Job #
class JobCreate(KanriCreateView):
	model = Job

class JobList(KanriListView):
	model = Job
	template_name = 'jobs/index.html'

	def get_context_data(self, **kwargs):
		context = super(JobList, self).get_context_data(**kwargs)
		m = Mentor.objects.filter(user = self.request.user)
		if m:
			context['mentor'] = m[0]
		return context

class JobDetail(KanriDetailView):
	model = Job
	template_name = 'jobs/detail.html'

class JobUpdate(KanriUpdateView):
	model = Job

class JobDelete(KanriDeleteView):
	model = Job
	success_url = reverse_lazy('jobs:index')

def register(request, pk):
	job = get_object_or_404(Job, pk = pk)
	mentor = get_object_or_404(Mentor, user = request.user)

	if request.method == 'POST':
		mentor.jobs_desired.add(job)
		mentor.save()

	return redirect('jobs:index')

def unregister(request, pk):
	job = get_object_or_404(Job, pk = pk)
	mentor = get_object_or_404(Mentor, user = request.user)

	if request.method == 'POST':
		mentor.jobs_desired.remove(job)
		mentor.save()

	return redirect('jobs:index')


# Job Allocation #
def allocate_job(request, session_id, job_id):
	session = get_object_or_404(DojoSession, pk = session_id)
	job = get_object_or_404(Job, pk = job_id)

	if request.method == 'POST':
		form = JobAllocationForm(request.POST, session = session, job = job)

		if form.is_valid():
			for mentor in form.cleaned_data['mentors']:
				j = JobAllocation(
					job = job,
					session = session,
					mentor = mentor
				)

				j.save()

			return redirect('planner:roster', session.term.id)
	else:
		form = JobAllocationForm(session = session, job = job)

	return render(request, 'jobs/allocate.html', {
		'session': session,
		'job': job,
		'form': form,
	})

class JobAllocationDelete(KanriDeleteView):
	model = JobAllocation
	success_url = reverse_lazy('jobs:index')

jobs/templates/jobs/allocate.html
{% extends 'base.html' %}

{% load bootstrap3 %}
{% load staticfiles %}

{% block site_title %} Add {{ job }} allocation to {{ session }} {% endblock %}
{% block body_title %} Add <b>{{ job }}</b> allocation to <b>{{ session }}</b>{% endblock %}

{% block content %}
	<form action="" method="post" class="form form-horizontal">
		{% csrf_token %}

		{% if form.errors %}
			<div class="alert alert-danger">
				{{ form.errors }}
			</div>
		{% endif %}
		
		{% bootstrap_form form layout='horizontal' %}

		{% buttons %}
			{% bootstrap_button 'Add Job Allocation' button_type='submit' %}
		{% endbuttons %}
	</form>
{% endblock %}

jobs/templates/jobs/detail.html
{% extends "generic_detail.html" %}
{% load display_pair %}
{% load bootstrap3 %}

{% block list_url %}{% url 'jobs:index' %}{% endblock %}
{% block edit_url %}{% url 'jobs:update' object.id %}{% endblock %}
{% block delete_url %}{% url 'jobs:delete' object.id %}{% endblock %}

{% block detail %}
	{{ object.name|display_pair:'Name' }}
	{{ object.description|display_pair:"Description" }}
	{{ object.location|display_pair:"Location" }}
	{{ object.get_time_display|display_pair:"Time" }}
{% endblock %}

jobs/templates/jobs/index.html
{% extends "generic_list.html" %}

{% load staticfiles %}

{% load bootstrap3 %}

{% block add_url %}
	{% url 'jobs:add' %}
{% endblock %}

{% block list %}
	<thead>
		<th class="col-md-2">Name</th>
		<th class="col-md-5">Description</th>
		<th class="col-md-2">Location</th>
		<th>Time</th>
		{% if perms.jobs.register_for_job %}
			<th>Register</th>
		{% endif %}
	</thead>
	<tbody>
		{% for job in object_list %}
			<tr>
				<td><a href="{{ job.get_absolute_url }}">{{ job.name }}</a></td>
				<td>{{ job.description }}</td>
				<td>{{ job.location }}</td>
				<td>{{ job.get_time_display }}</td>
				{% if perms.jobs.register_for_job %}
					{% if job in mentor.jobs_desired.all %}
						<form action="{% url 'jobs:unregister' job.id %}" method="post">
							{% csrf_token %}
							<td><button type="submit" class="btn btn-link">Unregister</button></td>
						</form>
					{% else %}
						<form action="{% url 'jobs:register' job.id %}" method="post">
							{% csrf_token %}
							<td><button type="submit" class="btn btn-link">Register</button></td>
						</form>
					{% endif %}
				{% endif %}
			</tr>
		{% endfor %}
	</tbody>
{% endblock %}